services:
  frontend:
    depends_on:
     - db
     - backend
    build:
      context: ./front        # Build context for frontend
      dockerfile: ../dockerfiles/front.Dockerfile # Custom Dockerfile location
    ports:
      - "3000:3000"
    restart: always
  
  backend:
    depends_on:
      db:
        condition: service_started
    build:
      context: ./back        # Build context for backend
      dockerfile: ../dockerfiles/back.Dockerfile  # Custom Dockerfile located in subfolder
    ports:
      - "4000:4000"
    restart: always

  db:
    image: postgres:13           # Use an image for PostgreSQL
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: /run/secrets/db_password
      POSTGRES_DB: mydatabase
    volumes:
      - data:/var/lib/postgresql/data

secrets:
   db_password:
     file: ./secrets/db_password.txt

volumes:
  data: